<!DOCTYPE html>
<html>
<head>
    <title>Laporan Stok Barang</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 11px; color: #333; line-height: 1.4; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        .header h2 { text-transform: uppercase; letter-spacing: 2px; color: #1a237e; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #f5f5f5; border: 1px solid #ccc; padding: 10px; text-align: center; font-weight: bold; color: #333; }
        td { border: 1px solid #eee; padding: 8px; vertical-align: middle; }
        
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        
        .sku-text { color: #666; font-size: 9px; font-family: 'Courier', monospace; margin-top: 2px; }
        .badge-low { color: #c62828; font-weight: bold; }
        .badge-ok { color: #2e7d32; }
        
        .summary-wrapper { margin-top: 20px; width: 100%; }
        .summary-box { 
            float: right; 
            width: 280px; 
            border: 1px solid #eee; 
            background-color: #f9f9f9; 
            padding: 12px; 
            border-radius: 8px; 
        }
        .clear { clear: both; }
        
        .footer { margin-top: 50px; text-align: right; font-style: italic; font-size: 10px; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h2 style="margin: 0;">InvenTrack System</h2>
        <p style="margin: 5px 0; font-size: 13px; font-weight: bold;">Laporan Inventaris & Nilai Aset</p>
        <p style="margin: 0; color: #666;">Tanggal Cetak: {{ date('d/m/Y H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="30">No</th>
                <th>Informasi Produk (Nama & SKU)</th>
                <th width="60">Stok</th>
                <th width="120">Harga Satuan</th>
                <th width="140">Subtotal Aset</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $index => $p)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>
                    <div style="font-weight: bold; font-size: 12px;">{{ $p->name }}</div>
                    <div class="sku-text">SKU: {{ $p->sku }}</div>
                </td>
                <td class="text-center">
                    <span class="{{ $p->stock <= $p->min_stock ? 'badge-low' : 'badge-ok' }}">
                        {{ number_format($p->stock) }}
                    </span>
                </td>
                <td class="text-right">Rp {{ number_format($p->price, 0, ',', '.') }}</td>
                <td class="text-right" style="font-weight: bold;">
                    Rp {{ number_format($p->stock * $p->price, 0, ',', '.') }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary-wrapper">
        <div class="summary-box">
            <table style="width: 100%; border: none; margin: 0;">
                <tr style="border: none;">
                    <td style="border: none; padding: 0; font-size: 11px;">Total Nilai Aset:</td>
                    <td style="border: none; padding: 0; font-size: 14px; color: #1a237e;" class="text-right">
                        <strong>Rp {{ number_format($totalAsset, 0, ',', '.') }}</strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="clear"></div>

    <div class="footer">
        Generated by InvenTrack Automation System
    </div>
</body>
</html>