<!DOCTYPE html>
<html>
<head>
    <title>Laporan Inventory</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 11px; color: #333; line-height: 1.4; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #444; padding-bottom: 10px; }
        .header h2 { text-transform: uppercase; letter-spacing: 2px; color: #1a237e; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #f5f5f5; border: 1px solid #ccc; padding: 10px; text-align: center; font-weight: bold; }
        td { border: 1px solid #eee; padding: 8px; vertical-align: middle; }
        
        .text-center { text-align: center; }
        .badge-in { color: #2e7d32; font-weight: bold; } /* Hijau buat masuk */
        .badge-out { color: #c62828; font-weight: bold; } /* Merah buat keluar */
        
        .footer { margin-top: 30px; text-align: right; font-style: italic; font-size: 10px; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h2 style="margin: 0;">InvenTrack System Report</h2>
        <p style="margin: 5px 0; font-size: 14px; font-weight: bold;">{{ $title }}</p>
        <p style="margin: 0; color: #666;">Dicetak pada: {{ date('d/m/Y H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="30">No</th>
                <th width="100">Waktu</th>
                <th>Produk & SKU</th>
                <th width="60">Tipe</th>
                <th width="50">Jumlah</th>
                <th width="100">User / Admin</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $index => $item)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td class="text-center">{{ $item->created_at->format('d/m/Y H:i') }}</td>
                <td>
                    <div style="font-weight: bold;">{{ $item->product->name }}</div>
                    <div style="color: #666; font-size: 10px;">SKU: {{ $item->product->sku }}</div>
                </td>
                <td class="text-center">
                    <span class="{{ $item->type == 'in' ? 'badge-in' : 'badge-out' }}">
                        {{ strtoupper($item->type) }}
                    </span>
                </td>
                <td class="text-center">{{ number_format($item->quantity) }}</td>
                <td>{{ $item->user->name ?? 'System' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" class="text-center" style="padding: 20px;">
                    Tidak ada transaksi pada periode ini.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by InvenTrack Automation System
    </div>
</body>
</html>