[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20", "npm-9_x"]

[phases.build]
cmds = [
    "composer install --ignore-platform-reqs --no-interaction --no-scripts --prefer-dist --optimize-autoloader",
    "npm install",
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"