[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "php82Extensions.gd",
    "php82Extensions.mbstring",
    "php82Extensions.xml",
    "php82Extensions.curl",
    "nodejs",
    "npm",
    "libpng",
    "libjpeg",
    "freetype"
]

[phases.build]
cmds = [
    "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev",
    "npm install",
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT"