[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20', 'php82Packages.gd', 'php82Packages.pdo_mysql', 'php82Packages.mbstring']

[phases.install]
# Kita paksa composer buat telen semua paket tanpa protes platform
cmds = ['composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-gd', 'npm install']

[phases.build]
cmds = ['npm run build']

[variables]
NIXPACKS_PHP_EXTENSIONS = 'gd,pdo_mysql,mbstring,xml,openssl,tokenizer'

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'